### ISSUE TITLE
Localized handlers

### ISSUE THREAD

**Issue by igorlauxen** [mrbandler/cds-routing-handlers#11]
Hello!

Does cds-routing-handlers support detecting Itranslation changes when user calls _entity(ID)/text_ path?

We want to block users from changing the translation fields of some specific entries which we will provide as standard by the application.

For example, in case I have the following entity

```
entity Foo : cuid {
  name           : localized String(255) not null;
  description : localized String(1000);
}
```

In the @Handler(Foo) I can detect if user is is changing the texts in case they use the following request:

[put] localhost:3001/odata/v1/FooService/Foo(bar)

body:

```
{
 "texts": [
   {"name": "Entwicklerin", "locale": "de"},
   {"name": "developer", "locale": "en"},
   {"name": "développeuse", "locale": "fr"}
   ]
 }
 ```
 
 However, we can also change the translations of the entities by calling the `/texts` path. Which is not fetch from the @Handler. The URL which we trigger is the following:
 
[post] localhost:3001/odata/v1/FooService/Foo(bar)/texts

Is there a way to detect changes in the localized fields in case user uses the url path `/texts`?

Thanks in advance!
Igor

**Comment by HeneryHawk** [comment]
Hi @igorlauxen,

yes, this should be possible, I just tested it successfully by using the Bookshop example.
You just have to register the handler to the `texts` property of the entity. Then you can register a method via `@BeforeUpdate` and `@BeforeCreate` on a PUT and POST request respectively.

```typescript
import { Handler, Req, BeforeUpdate, BeforeCreate, Data } from "cds-routing-handlers";

/**
 * GenreTextHandler handler.
 *
 * @export
 * @class GenreTextHandler
 */
@Handler("Genre.texts")
export class GenreTextHandler {
    /**
     * @memberof GenreTextHandler
     */
    @BeforeUpdate()
    @BeforeCreate()
    public async textModification(@Data() text: any, @Req() req: any): Promise<void> {
        console.log("UpdateTexts");
    }
}
```

Regards
Simon

**Comment by igorlauxen** [comment]
Thanks @HeneryHawk ! it worked =)
