### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mario-guenter** [mrbandler/cds-routing-handlers#15]
Error: 
![image](https://user-images.githubusercontent.com/7780170/147643475-686f0bc5-5e28-407a-92fa-91734af8af71.png)

Solution, see debug console:
![image](https://user-images.githubusercontent.com/7780170/147643719-98a16a92-3df0-4d86-9ffc-e9ebdcef579f.png)

**Comment by iDschepe** [comment]
Fix provided, waiting for release.
@mrbandler @HeneryHawk
