### ISSUE TITLE
New @sap/cds version does not inject @Jwt anymore

### ISSUE THREAD

**Issue by mrbandler** [mrbandler/cds-routing-handlers#3]
The previous method of extracting the JWT token is not feasable anymore as the token moved to a different object inside of the request object:
![1000ef20-de02-4f18-94ec-59cb1966f719](https://user-images.githubusercontent.com/7815115/73954977-e4773000-4902-11ea-9379-65d66b57dc48.jpg)

The token can now be found on the `req.attr` object:
![05acb484-7cb8-4e5d-a428-beabef870794](https://user-images.githubusercontent.com/7815115/73955088-18525580-4903-11ea-9744-c46e74d6de4d.jpg)

As this object already contains all the necessary information of the security context we might need a new decorator like @SecurityContext() that injects the whole object.
A typescript interface or class would be really handy to aswell.

**Comment by mariotcon** [comment]
Fixed in my PR, please merge.
